### ISSUE TITLE
query.WithLimit conversion panic

### ISSUE THREAD

**Issue by PurrBiscuit** [okta/okta-sdk-golang#27]
with the following config...

```
package main

import (
	"fmt"
	"github.com/okta/okta-sdk-golang/okta"
        "github.com/okta/okta-sdk-golang/okta/query"
)

func main() {
	config := okta.NewConfig().WithOrgUrl("https://xxxxxxx.oktapreview.com").WithToken("xxxxxxxxxxxxxxxxxxxxxxxxxxxx")
	client := okta.NewClient(config, nil, nil)

        qp := query.NewQueryParams(query.WithLimit(1))

	fmt.Println(qp)

	users, _, _ := client.User.ListUsers(qp)
	
	for _, user := range users {
		resp, _, _ := client.User.GetUser(user.Id, nil)
		profile := resp.Profile
		fmt.Println((*profile)["email"])
	}
}
```

...I get the following error when trying to use `query.WithLimit(1)`...

```
panic: interface conversion: interface {} is float64, not string

goroutine 1 [running]:
github.com/okta/okta-sdk-golang/okta/query.(*Params).String(0xc4200e3440, 0xd, 0x0)
	/Users/spurr/golang/src/github.com/okta/okta-sdk-golang/okta/query/query.go:206 +0x404
github.com/okta/okta-sdk-golang/okta.(*UserResource).ListUsers(0xc4200b3850, 0xc4200e3440, 0x1, 0x45, 0x0, 0x0, 0x0, 0xc42006bf78)
	/Users/spurr/golang/src/github.com/okta/okta-sdk-golang/okta/user.go:115 +0x1f1
main.main()
	/Users/spurr/src/okta-test/main.go:17 +0x151
```

It looks like [this switch block](https://github.com/okta/okta-sdk-golang/blob/master/okta/query/query.go#L202) is in need of an `float64` case to convert it to a string before tacking it onto the query string.

**Comment by viktor-yengovatov** [comment]
same for `query,Limit`
